import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Link href="/"> Main page </Link><br />
        <Link href="/page2">Page2</Link> <br />
        <Link href="/toConsider">List of considerations</Link>

        {children}
        <p>The root layout defines the basic layout of the first page\n
          Children appears to be a parameter passed in, containing page.tsx\n
          Can be used to maintain data across pages\n
          For current context: Load in calendar data, so maintained while navigating
        </p>
      </body>
    </html>
  );
}
